# Generated by Django 4.1.3 on 2022-12-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('date', models.CharField(default='2019', max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
                ('maladies', models.CharField(max_length=200)),
                ('wordFile', models.FileField(upload_to='wordFiles/')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('date', models.CharField(default='2019-01-01', max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
                ('maladies', models.CharField(max_length=200)),
                ('wordFile', models.FileField(upload_to='wordFiles/')),
            ],
        ),
    ]
